### ISSUE TITLE
Request for method for computing the integral

### ISSUE THREAD

**Issue by JoshuaMeyers** [aclyde11/regression_enrichment_surface#2]
* Regression Enrichment Surface version: 0.2.0
* Python version: 3.7.3
* Operating System: Mac Mojave

### Description

Hey Guys, nice paper and library. I'm interested in your approach, seems like this and the potentialnet rEF are still some of the only explorations of this topic.

Thought I'd open an issue with some thoughts, not sure if you're still maintaining this repo:
- It would be really useful to have a method on `RegressionEnrichmentSurface` to calculate the 2d integral. I'm not sure which variables I should be calculating it with to match the scores in your preprint.
- There are still some (I assume) legacy references to RegressionDetectionSurface which I guess was renamed to RegressionEnrichmentSurface
- I'm a little confused by the argument with a default negative percentage. How should I interpret this? 

Cheers in advance
J.

**Comment by aclyde11** [comment]
Hi Joshua, this repo has not been maintained but we still use the method for analyzing all our models effectiveness. I would be happy to implement things and make it work for more to start incorporating the ideas!

I agree, I should add the integral calculation (I can next week). The variables the integral goes over is the x,y axis of the plot. I actually didn't implement this since it isn't used in practice much. Which I can explain below.

The argument for the class essentially sets the bounds of the plot. The negative int is in log scale, so it's representing the number 10^-3 (for example). This means 10^-3 is the smallest unit of your data you want to look at. In the instance of virtual screening over 100,000 molecules a reasonable number might be -4 or -5, while a number of -1 is too big and doesn't capture the tippy top of the distribution while a number of -8 would imply a granularity that is too fine for 100,000 molecules. As a matter of a fact, I should have hidden this variable and let the code chose it. 

_tldr just pick one order of magnitude less than the length of rankings you will input into the code_


We look at the plots mostly. 
This idea comes from wanting metrics that are contextual. Non-contextual metrics like r2 scores, accuracy, etc bother me since they are hard to connect to actually convincing someone to use a model you make. This is where "context" comes in: 

- Imagine a PI wants to do some screening. She wants to know how much better a model is than previous VS techniques 
- She says I have the money for 100 expiriements.
- This means we will take the top 100 prediction from our model and ask how much of underlying (or "real") distribution did this capture? 10%? 50%? The top 100 predictions refers to the x axis, that is how many things you pull from your predictions. The specificity of the context (say we really feel comfortable with capturing anything in the top 1%) is the y axis. Therefore the value of the (x,y) point tells us how well our model would perform in this context, that is being able to do 100 predictions for which we hope to find the true top 1%. 

This slide might be helpful.
<img width="1191" alt="image" src="https://user-images.githubusercontent.com/17033421/119039864-58174200-b97a-11eb-98e1-c9cf14aec518.png">

**Comment by aclyde11** [comment]
essentially, this analysis works well for chaining surrogate models together and wanting to reason about where to set those filter bounds. For the picture I attached, the underlying model looks like it can with near 100% certainty correctly filter out anything that isn't in the top 1% (look at the point 10^-1,10^-2). This means if we use this model to filter out 99% of molecules, we would in theory not miss anything. 

this is super distinct from the metrics. I think this model actually has an r2 score of like 0.65 and some other metrics which sound "unimpressive" when in fact this is two orders of magnitude that could be offloaded to high-speed inference

**Comment by JoshuaMeyers** [comment]
Hey @aclyde11, Thanks for the detailed reply. Much appreciated! I am experimenting with methods for QSAR model selection where my data is imbalanced towards inactive molecules, so I'd like to evaluate the integral. For sure the plot allows a nice additional layer of interpretation. Very interesting comments regarding the failure of R2 here, this is the precise idea 😉. Thanks again!

**Comment by aclyde11** [comment]
@JoshuaMeyers I updated it the GitHub with the integral. I hope this helps. Also fixed the naming thing you mentioned. :) 

```python
    datas1 = [ i * random.random() for i in range(1000)]
    datas2 = [i for i in range(1000)]

    res = RegressionEnrichmentSurface(-2)
    res.compute(datas1, datas2, samples=15)
    #res.plot()
    print(res.compute_integral())
```

**Comment by JoshuaMeyers** [comment]
Hey Austin, thanks that's fantastic, look forward to trying it out. Would you be able to bump the version and push to pypi?

**Comment by aclyde11** [comment]
https://pypi.org/project/regression-enrichment-surface/0.3.0/

Should be all set. Let me know @JoshuaMeyers

**Comment by JoshuaMeyers** [comment]
Works great thanks @aclyde11!
